ALTER TABLE message RENAME COLUMN contenu TO content;

ALTER TABLE Private_message 
ADD COLUMN content VARCHAR(500) NOT NULL,
ADD COLUMN date_message TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN last_edit TIMESTAMP NULL;